# Generated by Django 6.0.3 on 2026-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=200, verbose_name='Cidade')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tipo_servico', models.CharField(max_length=200, verbose_name='Tipo de Serviço')),
                ('data_programada', models.DateField(verbose_name='Data Programada')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta Programada',
                'verbose_name_plural': 'Consultas Programadas',
                'ordering': ['data_programada'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('relatorio', 'Relatório Flip'), ('programados', 'Consultas Programadas')], max_length=50)),
                ('total_registros', models.IntegerField(default=0)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Importação',
                'verbose_name_plural': 'Importações',
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(blank=True, max_length=100, verbose_name='Número OS')),
                ('tipo_servico', models.CharField(max_length=200, verbose_name='Tipo de Serviço')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=200, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True, verbose_name='Data Abertura')),
                ('data_execucao', models.DateField(blank=True, null=True, verbose_name='Data Execução')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data Conclusão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.CharField(default='relatorio', max_length=50, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
