# Generated by Django 6.0.2 on 2026-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='endereco_normalizado',
            field=models.CharField(blank=True, max_length=500, verbose_name='Endereço (busca)'),
        ),
    ]
