# Generated by Django 6.0.2 on 2026-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_servico_endereco_normalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprefeitura', models.CharField(max_length=100, verbose_name='Subprefeitura')),
                ('tipo_nome', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('tipo_cod', models.CharField(blank=True, max_length=10, verbose_name='Código Tipo')),
                ('setor', models.CharField(blank=True, max_length=50, verbose_name='Setor')),
                ('logradouro', models.CharField(max_length=300, verbose_name='Logradouro')),
                ('referencia', models.CharField(blank=True, max_length=300, verbose_name='Referência')),
                ('nome_local', models.CharField(blank=True, max_length=300, verbose_name='Nome do Local')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Início vigência')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Fim vigência')),
                ('horario_inicio', models.CharField(blank=True, max_length=10)),
                ('horario_fim', models.CharField(blank=True, max_length=10)),
                ('frequencia', models.CharField(blank=True, max_length=20)),
                ('turno', models.CharField(blank=True, max_length=5)),
                ('opcoes_data', models.TextField(blank=True, verbose_name='Opções de data')),
                ('qtd_operadores', models.IntegerField(default=0)),
                ('qtd_veiculos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Programação de Serviço',
                'verbose_name_plural': 'Programações de Serviços',
                'ordering': ['subprefeitura', 'tipo_nome', 'setor'],
            },
        ),
    ]
