# Generated by Django 6.0.2 on 2026-03-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_programacaoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Finalização'),
        ),
        migrations.AddField(
            model_name='servico',
            name='fiscal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fiscal / Responsável'),
        ),
    ]
